### ISSUE TITLE
Dependencies with ranges not showing updates

### ISSUE THREAD

**Issue by lauritzsh** [tjunnone/npm-check-updates#126]
`ncu` suddenly stopped showing my outdated packages. It worked great a few days ago but not sure what changed since. A little log from my terminal:

```
~/Developer/flickr
$ cat package.json | head
{
  "name": "flickr-photo-browser",
  "private": true,
  "devDependencies": {
    "babel": "~5.8.20",
    "backbone": "^1.1.0",
    "backbone.paginator": "^2.0.0",
    "css-loader": "^0.16.0",
    "del": "^1.2.1",
    "extract-text-webpack-plugin": "^0.8.2",

~/Developer/flickr
$ npm v babel version
5.8.21

~/Developer/flickr
$ npm v backbone version
1.2.1

~/Developer/flickr
$ npm v backbone.paginator version
2.0.2

~/Developer/flickr
$ ncu

All dependencies match the latest package versions :)


~/Developer/flickr
$

```

If I remove the caret `~` or `^` both `ncu` and `npm outdated` works. Isn't `~` and `^` supposed to be relaxed by allowing ranges compared to specific `"1.0.0"`?

```
~/Developer/flickr
$ cat package.json | head
{
  "name": "flickr-photo-browser",
  "private": true,
  "devDependencies": {
    "babel": "5.8.20",
    "backbone": "1.1.0",
    "backbone.paginator": "2.0.0",
    "css-loader": "^0.16.0",
    "del": "^1.2.1",
    "extract-text-webpack-plugin": "^0.8.2",

~/Developer/flickr
$ ncu

 babel               5.8.20  →  5.8.21
 backbone             1.1.0  →   1.2.1
 backbone.paginator   2.0.0  →   2.0.2

Run with -u to upgrade your package.json


~/Developer/flickr
$ npm outdated
Package             Current  Wanted  Latest  Location
babel                5.8.21  5.8.20  5.8.21  babel
backbone              1.2.1   1.1.0   1.2.1  backbone
backbone.paginator    2.0.2   2.0.0   2.0.2  backbone.paginator

~/Developer/flickr
$
```

Because of the same weird behaviour I suspect something is wrong with `npm` but I could be trying to do something wrong here.

How come `ncu` only show updates when I set the specific versions compared to ranges with `~` and `^`?

**Comment by metaraine** [comment]
Hi, thanks for taking the time to inquire! This is a common misunderstanding with how npm and ncu work in regard to semver. I believe ncu is behaving as expected here, but I am open to ideas about how to communicate this more clearly.

`~5.8.20` is a range that will essentially include all non-major updates. If you run `npm update`, it will install `5.8.21` without needing to change the dependency version. `~5.8.20` is a range that includes `5.8.21` just as much as `~5.8.21`, so there is no need to change what is specified in your package.json.

`ncu` will generally give you a descriptive message if you need to run `npm updates` to install the latest within the specified range. If you *really* want to upgrade your package.json to `~5.8.21`, even though `~5.8.20` already includes `5.8.21`, you can generally run `ncu --updateAll`. 

The reason that ncu is telling you `All dependencies match the latest package versions ` and you're not getting the aforementioned descriptive message is because you already have `5.8.21` *installed*. So you literally have the latest version installed, and the dependency in your package.json is a range that includes it. So neither `ncu` nor `npm update` would change anything.

Removing `~` in your package.json (`5.8.20`) changes the dependency range to *not* include the latest (`5.8.21`), so ncu will happily tell you that you need to upgrade your package.json.

Let me know if that makes sense!

**Comment by lauritzsh** [comment]
Thanks for the explanation, it makes sense now! One question though, how come in your example that it shows `react-bootstrap ^0.22.6 -> ^0.24.0`?

![](https://cloud.githubusercontent.com/assets/750276/8864534/0788a4d8-3171-11e5-9881-8f7dcf634d14.png)

Since the new version is still within the range, should `ncu` _not_ show any updates related to `react-bootstrap` or is it because the installed (the one in `node_modules`) version is outdated? Same with `react-a11y` and `webpack` here.

I am not sure how to communicate this more clearly unfortunately, I guess it just needs an understanding of how `npm` works. I don't want to make it unnecessarily verbose :-) Unless it could be something like `All dependency ranges are satisfied, not updating` but I'm not sure how more clear that is.

**Comment by metaraine** [comment]
Versions before `1.0.0` are an exception—minor version updates are considered breaking.

However, that doesn't explain webpack in the example. I will investigate!

**Comment by lauritzsh** [comment]
Thanks for the help, I will probably use `save-exact` in the future so I can easily see changes. Might just be an outdated example, not sure if that was the case with `-ua`.

**Comment by lauritzsh** [comment]
I just realized webpack is using tilde `~` in the example. I guess that's why it is getting updated here.

**Comment by metaraine** [comment]
Exactly. Just noticed that myself.

`~` "include everything greater than a particular version in the same minor range"
`^` "includes everything greater than a particular version in the same major range"

http://semver.npmjs.com/
