### ISSUE TITLE
Why shouldn't rename npm package to ncu?

### ISSUE THREAD

**Issue by matth3wga0** [tjunnone/npm-check-updates#138]
Hello,

I found **npm-check-updates** accidentally, it's really useful, but there's one thing confused me. The node cli command is named **ncu**, usually I'll try `npm install ncu`.

**Comment by metaraine** [comment]
Hi! Thanks for your question. In fact, both commands work:

```
$ ncu
$ npm-check-updates
```

The library was originally named `npm-check-updates`. While any user could create an alias to make this shorter to type, in practice it was easier to build in `ncu` as an alternative command so that everybody has it out of the box, and thus all examples, issues, and discussions can use the easier-to-type command. 

Changing the package name itself would have left the hundreds of existing users unable to upgrade. The best solution in that scenario is to push a patch to the old package that provides a deprecation warning, urging users to switch to the new package. This seems like it causes more trouble than simply adding an alias to the new package.

Lastly, the package is more easily searchable online, on npm, and on github, with the name "npm-check-updates" instead of "ncu".

Hope that clarifies the situation!

**Comment by matth3wga0** [comment]
Wish one day **npm-check-updates** will be merged into **npm**, so we can `npm check-updates`.
