### ISSUE TITLE
ncu -u says it upgraded my package.json, but it didn't

### ISSUE THREAD

**Issue by callumlocke** [tjunnone/npm-check-updates#153]
I love this tool, thanks for making it. Small issue though...

```sh
$ ncu -u

The following dependency is satisfied by its declared version range, but the installed version is behind. You can install the latest version without modifying your package file by using npm update. If you want to update the dependency in your package file anyway, use --upgradeAll.

 eslint  ^1.6.0  →  ^1.7.1

Upgraded /Users/callum/code/foo/package.json
```

...but my package.json has **not** been updated. It still lists eslint 1.6.0.

On further digging, I see that this is the new intended behaviour (apparently it's now `-a` to upgrade everything).

But it's confusing that it says `Upgraded /Users/callum/code/foo/package.json` even though it didn't change anything.

**Comment by metaraine** [comment]
Thanks, I agree the message is confusing when the `-a` flag is not used, and there are no unsatisfied dependencies that are actually upgraded.

I will correct this in the next version. Likely, the output is going to change a bit to accommodate the new asynchronous output that will show updates for individual packages immediately as they return instead of waiting for them all at the end.
