### ISSUE TITLE
After I used this my gulp has stopped working

### ISSUE THREAD

**Issue by jitendravyas** [tjunnone/npm-check-updates#155]

**Comment by metaraine** [comment]
Hi Jitendra. Thanks for reporting.

`npm-check-updates` is actually *meant* to break your dependencies. It breaks them so that you can get the latest and greatest versions, and then deal with backwards-incompatible changes manually. If you don't want to upgrade to backwards-incompatible changes, simply use `npm update`.

Are you using source control? If so, I would recommend reverting to the last commit, and then upgrading packages individually to see what the culprit is. Then you can find out which backwards-incompatible change is causing the problem, and take whatever migrations steps are needed.
