### ISSUE TITLE
Can't limit version's patch part

### ISSUE THREAD

**Issue by koorgoo** [tjunnone/npm-check-updates#164]
According to [semver](https://docs.npmjs.com/misc/semver#tilde-ranges-1-2-3-1-2-1) tilde limits patch part. 
E.g. `~0.19.1` allows versions range `0.19.1 <= version < 0.20`.
`ncu` does not respect this rule and always updates such versions.

**Comment by metaraine** [comment]
Hi Dima. This is expected behavior. The purpose of npm-check-updates is to update versions *beyond* what semver allows. This give you full control over upgrading to backwards-incompatible versions. If you want to stay within semver, just use `npm update`. There is no need to change your package.json in that case.

**Comment by koorgoo** [comment]
Thanks for your answer, @metaraine.
