### ISSUE TITLE
Grouping the output

### ISSUE THREAD

**Issue by sapegin** [tjunnone/npm-check-updates#166]
It would be nice if ncu shows `dependencies` and `devDependencies` separately. Something like this:

```
❯ ncu

dependencies:

 babel-core                   ~5.8.30  →  ~6.1.21
 babel-loader                   5.3.2  →    6.1.0
 css-loader                    0.21.0  →   0.23.0
 extract-text-webpack-plugin    0.8.2  →    0.9.1
 glob                          5.0.15  →    6.0.1
 postcss-loader                 0.7.0  →    0.8.0
 react-codemirror               0.1.7  →    0.2.0
 react-docgen                   2.3.1  →    2.4.0

devDependencies:

 webpack                       1.12.2  →   1.12.6
 webpack-hot-middleware         2.4.1  →    2.5.0
 webpack-merge                  0.2.0  →    0.3.0
 babel-eslint                   4.1.3  →    4.1.5
 eslint                         1.7.3  →    1.9.0
 eslint-plugin-react            3.6.3  →    3.8.0

Run with -u to upgrade package.json
```

What do you think about that?

**Comment by subjectix** [comment]
:+1:

**Comment by metaraine** [comment]
Hi Artem. That's a good suggestion, and makes sense for differentiating the two types of dependencies.

Would this suffice for the time being?

```
ncu --dev && ncu --prod
```

I am hesitant to get into grouping, as there are many possible dimensions that people might want to group (dev/prod, satisfied/unsatisfied, installed/not installed, etc).

**Comment by sapegin** [comment]
I’ll try that, thanks! Should be enough.

**Comment by raineorshine** [comment]
Sure, good idea. 

Added `--format dep` in `v19.2.0`.

## format

Usage:

    ncu --format [value]

Modify the output formatting or show additional information. Specify one or more comma-delimited values.

<table>
  <tr><td><b>dep</b></td><td><b>Prints the dependency type (dev, peer, optional) of each package.</b></td></tr>
  <tr><td>group</td><td>Groups packages by major, minor, patch, and major version zero updates.</td></tr>
  <tr><td>installedVersion</td><td>Prints the exact current version number instead of a range.</td></tr>
  <tr><td>lines</td><td>Prints name@version on separate lines. Useful for piping to npm install.</td></tr>
  <tr><td>ownerChanged</td><td>Shows if the package owner has changed.</td></tr>
  <tr><td>repo</td><td>Infers and displays links to the package's source code repository. Requires packages to be installed.</td></tr>
  <tr><td>time</td><td>Shows the publish time of each upgrade.</td></tr>
</table>
