### ISSUE TITLE
Compatibility with npm 3.4.1 @latest updates

### ISSUE THREAD

**Issue by sgwatgit** [tjunnone/npm-check-updates#171]
The options for npm-check-updates include this one
```
-t, --greatest           find the highest versions available instead of the
                         latest stable versions (alpha release only)
```
Does this need more explanation or an update because of how [npm 3.4.1](https://github.com/npm/npm/releases/tag/v3.4.1) will handle `npm install ...` by grabbing the latest (even pre-release in some situations)?

**Comment by metaraine** [comment]
Hi Sean, thanks for bringing this to my attention. I'm confused because I thought that's how npm install worked before!

This option is still valid for allowing npm-check-updates to install prerelease versions. By default npm and ncpm-check-updates install the `latest` tag. Adding `-t` or `--greatest` will instead install the "greatest" or "highest" number version available, even if it is greater than `latest`.
