### ISSUE TITLE
Option to automatically update but only on patch level

### ISSUE THREAD

**Issue by scic** [tjunnone/npm-check-updates#178]
I have the following feature request:
The command "ncu -u" updates all dependencies. I would like an option to only do patch level updates automatically, since these are relatively save updates.
e.g. update 1.4.1 to 1.4.2 but don't update it if the new version is 1.5.3.

I'm aware that there is the option to just specify 1.4.x in the package.json (or bower.json), but I really like to have explicit versions in them.

This would enable a use case where we would want to update patch level updates automatically in a nightly script. But we would still do a manual run and view the changelog for minor and major changes.

A bonus would be the same feature for the minor level as well.

**Comment by metaraine** [comment]
Hi Daniel. Thanks for your suggestion! I understand what you are requesting.

Patch updates are indeed safe as long as library authors are following semver, and it makes since to always upgrade your dependencies to the latest patches.

As you mentioned, if you specify a dependency as `1.4.x` or `^1.4.0`, then the latest patch or minor version, respectively, will automatically be upgraded when running `npm install` or `npm update`.

With respect, I would argue that there is no reason to explicitly specify `1.4.2` in your package.json instead of `1.4.x` or `^1.4.0`. Maybe you prefer seeing the explicit versions aesthetically, but there is no functional reason to include them. This is why semver exists. I would recommend embracing semver and using the range operators like `^` or `~`. You can then run `npm update` regularly to keep non-breaking changes up-to-date.
