### ISSUE TITLE
Update available notification doesn't display when running ncu

### ISSUE THREAD

**Issue by jml6m** [tjunnone/npm-check-updates#192]
When I ran just the command `ncu`, it printed out a list of available dependency updates.

It wasn't until I ran `ncu -u` that it printed a window saying:
┌─────────────────────────────────────────────────┐
│ Update available: 2.5.5 (current: 2.3.4)        │
│ Run npm install -g npm-check-updates to update. │
└─────────────────────────────────────────────────┘

I would have liked to update `ncu` first, then run `ncu -u`...if only the notification came earlier.

**Comment by metaraine** [comment]
Hi, thanks for reporting. ncu uses [update-notifier](https://github.com/yeoman/update-notifier) to report updates that are available for ncu itself (although ncu -g also works). `update-notifier` runs asynchronously and caches its results to not affect the performance of its host. This can result in updates not being reported immediately. My understanding is that this was a purposeful tradeoff. Since this behavior is baked into `update-notifier`, and does not seem too problematic, it is unlikely that this behavior will be changed.
