### ISSUE TITLE
Would love a flag that just shows patch version updates available

### ISSUE THREAD

**Issue by zackarychapple** [tjunnone/npm-check-updates#212]
Part of the process for a project I work on is we lock down the versions of dependencies when we cut tags.  It would be great to be able to see what patch versions are available rather than just latest version.

**Comment by metaraine** [comment]
Thanks for your suggestion, Zack. The philosophy behind ncu is that we want to break dependencies in order to force upgrade to the latest version. Constraining dependencies within ncu would, in my opinion, confuse the main purpose. npm and semver themselves are designed to support varying levels of strictness of dependency constraint. Others have suggested different ways of constraining version numbers with ncu and they have been rejected for the same reason.

**Comment by zackarychapple** [comment]
Fair enough.  I appreciate the response.  Thank you for replying.
