### ISSUE TITLE
Feature: meteor npm packages.json support

### ISSUE THREAD

**Issue by mcorb** [tjunnone/npm-check-updates#213]
The Meteor frameworks supports npm dependencies via a custom JSON file, "packages.json"

The format (described at https://github.com/meteorhacks/npm) is similar to npm's "dependencies" section alone, except for the restriction that version numbers must always be stated explicitly.

Presumably this can be implemented as a third packager backend, that mostly reuses the existing npm machinery?

**Comment by metaraine** [comment]
Since it still uses the npm registry, the only thing that needs to change is the package file format. An easy solution without modifying ncu would be to pipe the meteor-friendly "packages.json" through a bash string concat that wraps the content in "{ dependencies: ... }" before handing it off to ncu. Then strip off the dependencies wrapper before saving it back to disk. (On my mobile right now, but let me know if that does not make sense and I could provide a more thorough description when I'm back at my computer.)
