### ISSUE TITLE
Filter packages by version

### ISSUE THREAD

**Issue by clekstro** [tjunnone/npm-check-updates#230]
First off, thanks for making this! I'm excited to use this to automate some weekly maintenance, but I'm needing to restrict the returned packaged based on version numbers.  Specifically, I'd like to avoid any package that contains either *alpha* or *beta* in the package version (for stability reasons). My thought now would be to either filter via regex (similar to the current name filter behavior), or to ignore any packages with non-numeric + `.` values.

I'm happy to submit a PR if this is something you'd find interesting. 

Thanks!

**Comment by metaraine** [comment]
Thank you for the offer! Glad to get some more help through pull requests.

By default ncu fetches the version specified in the "latest" tag, which
library authors should not use for pre-release versions. I wonder if the
addition you suggested is not really necessary because of this. I would
recommend educating library authors about proper use of the latest tag.

That said, there's nothing preventing library authors from ignoring this
best practice and publishing an alpha to latest anyway, so I could see how
you might want this safeguard in place. If so, I would suggest adding
--filterVersion and --rejectVersion options. Ideally they would parallel
the behavior of --filter and --reject.

One challenge is that ncu just fetches latest and does not fetch previous
versions. So if you have a library at 1.0.0 and there is both a 2.0.0 and a
3.0.0-alpha published to npm, then if you ignore the alpha it won't upgrade
at all, even though 2.0.0 is available. You will have to add a function to
package-managers/npm.js to allow filtering of packages when all versions
are returned.

**Comment by clekstro** [comment]
Thanks for the feedback and hints on where/how to make changes. I'll submit a PR when I've gotten something together!

**Comment by metaraine** [comment]
Sounds good! Let me know if you need any help!

The code base is about a B or B- in terms of clarity. Good unit test
coverage though.

-Raine

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.
