### ISSUE TITLE
Feature: Ignoring locked dependencies

### ISSUE THREAD

**Issue by amilajack** [tjunnone/npm-check-updates#272]
A feature that ignored updating locked dependencies would make much more sense.

Maybe it should be in the form of something like this?
```
ncu --ignore-locked
```

Thoughts?

**Comment by raineorshine** [comment]
Hi! Thanks for the idea. I need to be educated. What are locked dependencies? I googled it but different things came up.

**Comment by amilajack** [comment]
Sorry for the lack of clarity. I don't think its called that officially. By locked I mean dependencies that force an exact semvar to be installed:


```
{
  superCoolModule: 0.0.1 //   <-- this will install exactly 0.0.1.
  otherModule: ^0.0.1 //   <-- this will install anything until major semvar
}
```

**Comment by raineorshine** [comment]
Okay, I understand now. Can you describe a use case in which this would be needed? Generally npm-check-updates is used specifically for the purpose of upgrading exact versions, i.e. it lets you break out of semver itself, while maintaining your range specifiers.

**Comment by amilajack** [comment]
I see. On a side note, do you know why the tests are failing? It would be great if we could get them working.

**Comment by raineorshine** [comment]
Actually, npm-check-updates, is meant to be used to upgrade to backwards-incompatible versions. It is meant to break things. You can run npm-check-updates to force upgrade all dependencies, run your unit tests to see what breaks, then commit fixes to your tests. If you want to ensure that you do not break your code, `npm update` works fine afaik. Does this help clarify? Let me know if I'm missing something.

(The tests are only failing on node v0.12 currently, due to the newest version of eslint using es6 syntax. I am going to remove v0.12 from the .travis.yml if there isn't an obvious way to disable linting just for that engine.)

**Comment by amilajack** [comment]
I've made a PR for that! Thanks for explaining.
