### ISSUE TITLE
Upgrade npm to stable v3.10.7

### ISSUE THREAD

**Issue by nikolay** [tjunnone/npm-check-updates#275]

**Comment by raineorshine** [comment]
Hi! Thanks for reporting. The specified version range, `^3.10.6`, actually includes `v3.10.7` so no reason to upgrade. New installs of `npm-check-updates` or running `npm update` will get the latest version. (As described in the [semver](http://semver.org) spec.)

**Comment by nikolay** [comment]
@raineorshine Didn't see that, sorry, but although I have npm v3.10.7 installed in the system with node.js v6.7.0, your package install v3.10.6.

**Comment by raineorshine** [comment]
`3.10.6` was probably the latest at the time of install. Even though `^3.10.6` includes `3.10.7` and would install the latest on a fresh install. npm modules don't re-install all their dependencies each time they are run though. They don't need to, as the version they are coded against is what they were built against. I'm not sure though if `npm update` does a deep install, updating all nested packages.

More importantly, what issues is this mismatch causing for you? That will help me better assess the impact of having an older version of npm used by ncu than what is on the user's system.

(As an aside, there have been some issues before having to do with the difference between the version of npm installed on the user's system and that used by ncu. I need to understand better which one is needed where so that I can fix those issues. Likely there is some place that needs to use the system install instead of the local install.)
