### ISSUE TITLE
Update packages with caret only

### ISSUE THREAD

**Issue by JaKXz** [tjunnone/npm-check-updates#281]
Hi - thanks for a great project :)

Is there any way to have `ncu -u` only apply to the packages whose versions are specified with the (`^`) caret? This way I can mark packages with the caret for packages that I trust to release non-breaking features and fixes and conveniently update to those.

I did a quick search through the issues for this but it might just be an edge case, which is fine.

**Comment by raineorshine** [comment]
Hi! Thanks for the question. There is not currently a way to only apply ncu to packages with specific version patterns. The `--filter` option can be used to filter by package name, and the `--semverLevel` flag can be used for some very broad filtering of version patterns, but it doesn't have more granular filtering.

Since ncu is *designed* to break your project by upgrading to breaking versions (if you wanted non-breaking versions, you would just use `npm update` and the normal semver semantics), I would recommend identifying packages that you *don't* want to upgrade with ncu, and selectively filter those out by name with `--reject`.

If my suggestion is not a good solution for your problem, please describe your overall use case in more detail and I can respond regarding ncu's current capabilities, recommended usage, and possible refinements.

**Comment by JaKXz** [comment]
@raineorshine thanks for the reply, and sorry for the delay! What I was looking for was [`npm update --save`](https://docs.npmjs.com/cli/update#recording-updates-with---save).

**Comment by raineorshine** [comment]
Great!
