### ISSUE TITLE
Latest version of plotlyjs not on github

### ISSUE THREAD

**Issue by scheung38** [tjunnone/npm-check-updates#282]
$ ncu -u
⸨░░░░░░░░░░░░░░░░░░⸩ ⠹ :

But plotlyjs in bower.json for example 

  "dependencies": {
    "plotlyjs": "plotly#^1.16.2"
  },

is still old version? Whereas cdn is 1.17.3

https://cdn.plot.ly/plotly-latest.min.js
/**
- plotly.js v1.17.3

But since plotlyjs is dependent on d3js but it was installed via 

$ npm install d3 --save

package.json:

"d3": "^4.2.6",

so do I need to install both d3 as well as plotlyjs using the same npm or bower as they are in different package.json and bower.json files?

**Comment by raineorshine** [comment]
Hi! Thanks for reporting. It looks like this is a specific issue with plotly which has nothing to do with ncu. The latest version of plotly on github is indeed 1.16.2:

```
$ bower info plotly
bower not-cached    https://github.com/b-pos465/plotly_bower.git#*
bower resolve       https://github.com/b-pos465/plotly_bower.git#*
bower checkout      plotly#1.16.2
bower resolved      https://github.com/b-pos465/plotly_bower.git#1.16.2

{
  name: 'plotlyjs',
  authors: [
    'Stefan Bechert <bechert@infai.org>'
  ],
  description: 'Bower package for plotlyjs.',
  main: 'plotly.js',
  moduleType: [],
  keywords: [
    'Plotlyjs'
  ],
  license: 'MIT',
  homepage: 'https://github.com/b-pos465/plotly_bower',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ],
  version: '1.16.2'
}

Available versions:
  - 1.16.2
  - 1.4.1
  - 0.0.2
  - 0.0.1
```

They don't seem to support [bower or npm](https://plot.ly/javascript/getting-started/). I don't know where the CDN version is coming from, but you could let them know that the github repo is behind. Otherwise, you may have to use the CDN directly.
