### ISSUE TITLE
Explanation required on the results of ncu command

### ISSUE THREAD

**Issue by st-clair-clarke** [tjunnone/npm-check-updates#284]
When I run ncu, I get the following

[J:\workspace\angular2\ts\epimss]ncu

   ╭──────────────────────────────────────────────╮
   │                                              │
   │       Update available 2.8.0 → 2.8.5         │
   │   Run npm i -g npm-check-updates to update   │
   │                                              │
   ╰──────────────────────────────────────────────╯

[..................] | :
 @angular/common                            2.0.0  →          2.0.2
 @angular/compiler                          2.0.0  →          2.0.2
 @angular/core                              2.0.0  →          2.0.2
 @angular/forms                             2.0.0  →          2.0.2
 @angular/http                              2.0.0  →          2.0.2
 @angular/platform-browser                  2.0.0  →          2.0.2
 @angular/platform-browser-dynamic          2.0.0  →          2.0.2
 @angular/router                            3.0.0  →          3.0.2
 @types/request                            0.0.30  →         0.0.31
 @types/validator                         ^4.5.28  →        ^5.7.33
 class-validator                           ^0.5.0  →         ^0.6.1
 rxjs                               5.0.0-beta.12  →     5.0.0-rc.1
 validator                                 ^5.6.0  →         ^6.0.0
 angular-cli                        1.0.0-beta.15  →  1.0.0-beta.17
 codelyzer                                ~0.0.26  →  ~1.0.0-beta.1
 jasmine-core                               2.4.1  →          2.5.2
 jasmine-spec-reporter                      2.5.0  →          2.7.0
 karma                                      1.2.0  →          1.3.0
 protractor                                 4.0.5  →          4.0.9
 ts-node                                    1.2.1  →          1.4.2
 tslint                                    3.13.0  →         3.15.1
 typescript                                 2.0.2  →          2.0.3

The following dependencies are satisfied by their declared version range, but the installed versions are behind.
 You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, use ncu -a/--upgradeAll.

 @types/lodash   ^4.14.36  →  ^4.14.37
 form-data         ^2.1.0  →    ^2.1.1
 lodash           ^4.16.2  →   ^4.16.4
 @types/jasmine   ^2.2.30  →   ^2.5.35

Run ncu with -u to upgrade package.json

1. If I 'Run ncu with -u to upgrade package.json' only the last four entries below will be updated?
 @types/lodash   ^4.14.36  →  ^4.14.37
 form-data         ^2.1.0  →    ^2.1.1
 lodash           ^4.16.2  →   ^4.16.4
 @types/jasmine   ^2.2.30  →   ^2.5.35

2. Or all the above behind versions will be upgraded?

Thanks.

**Comment by raineorshine** [comment]
Hi! Thank you for question. Given your example:

- If you run `ncu -u`, it will update all dependencies *except* @types/lodash, form-data, lodash, and @types/jasmine. This is the default behavior because there is no functional need to change the version numbers in your package.json for these packages; they are already listed as ranges that include the latest. A simple `npm update` will bring your packages up to date without changing your package.json.

- If you run `ncu -a`, *all* packages listed will be upgraded to the latest. This is a non-default behavior that's not strictly necessary, yet has been requested by enough from people to be provided as an option.

Hope that helps!

As long as your package.json is in version control, you can also try either command and see how it is modified.

**Comment by st-clair-clarke** [comment]
Thanks a million.

**Comment by raineorshine** [comment]
Sure!
