### ISSUE TITLE
Why are beta packages showing up?

### ISSUE THREAD

**Issue by kitsunde** [tjunnone/npm-check-updates#285]
```bash
$ npm-check-updates
[INFO]: You can also use ncu as an alias
⸨░░░░░░░░░░░░░░░░░░⸩ ⠼ :
 ember-cli-release  ^0.2.9  →  ^1.0.0-beta.2
 ember-data         ^2.8.1  →  ^2.9.0-beta.2
 ember-moment        6.1.0  →   7.0.0-beta.3

The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, use ncu -a/--upgradeAll.

 ember-ajax                       ^2.5.1  →  ^2.5.2
 ember-cli-qunit                  ^3.0.1  →  ^3.0.2
 ember-cordova                    ^0.3.2  →  ^0.3.4
 ember-export-application-global  ^1.0.5  →  ^1.1.1
 ember-notify                     ^5.1.1  →  ^5.1.3
 glob                             ^7.1.0  →  ^7.1.1
```

**Comment by raineorshine** [comment]
Hi! Thanks for the question! The main issue you are experiencing is what I would call non-standard publishing behavior by the authors of those three libraries; their beta has been released on the "latest" tag on npm, so for all intents and purposes, the latest, stable version is `v1.0.0-beta.2`, etc.

Observe:

```
$ npm view ember-data dist-tags
{ latest: '2.9.0-beta.2', beta: '2.9.0-beta.4' }
```

My guess is that this was purposeful on the part of the ember team in order to fully expose `beta.2` to the community while keeping the "beta" label. Nevertheless, this is not the typical approach, where "latest" is expected to be the latest stable version. As long as these package authors are releasing betas on the "latest" tag, the tooling ecosystem has no good way to distinguish a "real" stable version from a beta being published as stable. (Technically you could parse the beta out of the version number on a per-tool basis, but yikes! that seems to defeat the whole purpose of versioning and tags.)

Hope that explains the background behind the behavior you are seeing, which is expected from ncu's point of view. If you find this behavior problematic, I recommend creating an issue on those package's repos.
