### ISSUE TITLE
must explicitly type `ncu --packageFile=package.json`

### ISSUE THREAD

**Issue by the-simian** [tjunnone/npm-check-updates#288]
I'm not sure what to do here but every time if I don't explicitly specify my package file it fails to complete. Would it make sense to check for a packagefile that is conventionally package.json first?

**Comment by raineorshine** [comment]
What OS are you running? On some Windows systems, due to the terminal behavior, ncu waits for stdin. You can run `ncu --loglevel verbose` to see if this is the case.

**Comment by the-simian** [comment]
Yeah, that's the case. I am running windows, I don't experience this issue on my osx or linux machines. Its not a big deal, I just must simply always run with that flag. I figured you'd want the library to be 'out of the box' for everyone, so I wanted to share what I've come across. I love the tool, just gotta type that everytime is all.

**Comment by raineorshine** [comment]
As far as I can tell, this is an issue with the Windows terminal incorrectly giving a signal to node that `stdin` is open and the program should thus wait until the stream is closed. You can read more about the issue: #136. I have not yet heard an argument that `ncu` is doing it incorrectly, although if there is a best practice for accepting `stdin` in a cross-platform way that is different, I would love to hear about it.

Still, it is disappointing that the issue is so widespread for window users, and in the next major version of ncu I might declare defeat and make `stdin` opt-in instead of autodetected to avoid the issue completely.

**Comment by the-simian** [comment]
Cool, sounds like a pretty even-handed reaction. Sorry to be the bearer of news. If it helps any I'm using a custom terminal based on cygwin, at the moment. I think you'll find a lot of the folks when they are working on windows will basically be using something similar, like babun, console 2, conemu etc. You might get somone using powershell now and then. I use normal console stuff on other platforms. It comes with the territory of working in this ecosystem, so its worth knowing about.

Thanks again for the great module, appreciate the work.

**Comment by raineorshine** [comment]
Thanks!
