### ISSUE TITLE
Update dependencies of dependencies

### ISSUE THREAD

**Issue by mldmelissa** [tjunnone/npm-check-updates#299]
Is there a way to update dependencies of other dependencies with npm-check-updates? For example, Project A depends on Project B, which depends on Project C.

-ProjectA
          -ProjectB
                     -ProjectC

If I do $ncu on Project A using npm-check-updates, it only checks for updates on Project B, and does not automatically check for Project C updates as well. 

Is there a setting that can check for updates of layered dependencies and then update them on ProjectA?

**Comment by raineorshine** [comment]
Hi! There is currently not a way to check for updates on dependencies. npm updates packages without including breaking changes. ncu forces upgrades with breaking changes, so it's meant more for package authors who want to force upgrades and then fix any regressions that arise. Since most dependencies are from other authors, you wouldn't be able to fix any breaking changes of them yourself most likely. For these reason, I'm not sure if checking for updates of dependencies of dependencies makes sense. You should probably stick with `npm update`. Does this help?

**Comment by mldmelissa** [comment]
@raineorshine what exactly do you mean by "breaking changes"? Also, I'm having trouble getting npm update to work properly. I've read that this might be an issue with the newest version of npm?

**Comment by raineorshine** [comment]
Breaking changes are changes that are not backwards-compatible. For example, a function used to take one parameter, and now it requires two parameters. Normally npm wouldn't allow you to upgrade to a breaking change in a dependency (which is a good thing, to keep your code from breaking), but ncu forces the upgrade so that you can then have the latest versions and deal with any changes that need to occur in your code to make it compatible again.

I'm not aware of any issues with the latest version npm. There are some environment-specific issues that other users have reported. If you don't see it in the list of known issues on the README, please create an issue with all the necessary details and I will investigate. Thanks!
