### ISSUE TITLE
Preserve colours when using "exec('ncu -g')"

### ISSUE THREAD

**Issue by carmelone** [tjunnone/npm-check-updates#305]
I'm using:

```javascript
const exec = require('child_process').exec;

exec('ncu -g', function (err, stdout, stderr) {
    if (err) {
      console.log(stderr);
    }
    console.log(stdout);
  });
```

Everything works, but is everything gray, black and white.

How to preserve colours?

I'm in Windows 10 x64.

**Comment by raineorshine** [comment]
Try this:
```
exec('FORCE_COLOR=1 ncu -g', ...)
```

https://github.com/chalk/chalk#chalksupportscolor

**Comment by carmelone** [comment]
On Windows it doesn't work, I need to use `set FORCE_COLOR=1 && ncu...`.
But we can't use `--color`, please?

**Comment by raineorshine** [comment]
Oh good! Sorry I was not familiar with how to set environment variables on Windows. Good catch!

If I add --color, it would override terminal auto detection, so I don't want to do that for all users. If someone is specifically invoking ncu with child_process.exec, this should be an adequate workaround.

**Comment by carmelone** [comment]
I don't understand this: `If I add --color, it would override terminal auto detection`... What you mean?

**Comment by raineorshine** [comment]
I was referring to `--color` for chalk. If it is behind a `--color` flag on ncu, then it wouldn't be a problem, as it would be opt-in, so you can disregard my last statement!

I will happily accept a pull request for this feature, otherwise I would consider it a lower priority issue since it is only effects a specific use case on a specific platform and there is a simple workaround.
