### ISSUE TITLE
[FEATURE REQUEST] Exclude prerelease tags while checking for updates

### ISSUE THREAD

**Issue by karanjthakkar** [tjunnone/npm-check-updates#308]
I was wondering if an extra flag to exclude prerelease tags is something you would consider adding? 

_Example_:

- Current `package.json`:

```json
...
"dependencies": {
    "react": "0.14.6"
}
```

- Update suggested by `ncu -p --semverLevel major -u` -> `0.15.0-alpha.1`

- Actual version I want: `0.14.8` (which is the latest after `0.15.0-alpha.1`)

I'd be happy to work on it and get it in!

**Comment by raineorshine** [comment]
The main purpose of npm-check-updates is to force your dependencies to the latest version. If you want to constrain the version to a given range, npm and normal semver semantics should allow you to do that. For example, if you specified your dependency as `^0.14.6`, then running `npm update` would automatically install `0.14.8` without upgrading it to the next major version.

What do you think?

**Comment by karanjthakkar** [comment]
@raineorshine So I don't know how the workflow is for most people, but for me:

1. Each dependency is specifically defined in the package without `~` or `^`, etc. eg: `0.14.6`
2. Every few weeks I run `ncu` to check for new updates
3. I install the latest non-prerelease version that is available for every package by going through the changelog for each dep.

So while doing step `3`, I sometimes find that some packages have released prerelease versions that I don't want to install. So I manually check which was the last stable version and use that.

Does that make sense?

**Comment by raineorshine** [comment]
Okay, that makes sense. It looks like the latest version of react is `15.4.1`. Is there a reason you are not wanting to upgrade to the latest? If I can understand your needs better I can think about how npm-check-updates can best be used in your situation.

Can you confirm that you are using the latest version of npm-check-updates btw? I am unable to reproduce the result of `0.15.0-alpha.1` that you are getting.

**Comment by karanjthakkar** [comment]
So if you have `0.14.6` in your dependencies and do a `ncu -p --semverLevel major`, it will say the next version that matches my semver query is `0.15.0-alpha.1`.

The reason for me not upgrading to the latest (15.4.1) is because its a completely new version with breaking changes. I can't do it often. So I just want to frequently do non-breaking version updates for my project. For breaking version updates, I have to plan them but its definitely not too frequent.

Does this seem like a use case that ncu should fulfill?

**Comment by raineorshine** [comment]
Could you please confirm what version of npm-check-updates you are running? I assume it is the latest but I would like to double check since we seem to be getting different behavior with checking against `0.14.6`.

I think ncu should definitely handle your use case, it's just a question of how. I'm already regretting accepting a pull request for the `--semverLevel` flag, which I believe adds additional complexity with little added value. As described, `--semverLevel major` "find[s] the highest version within "major"". Since the major version number of `0.14.6` is `0`, then `--semverLevel major` simply finds the highest number that starts with `0.`, hence `0.15.0-alpha.1`. Not including prerelease versions is one more step that must be taken to get the functionality you desire, and it is not yet implemented.

Considering that I am already tempted to remove `--semverLevel` in the next major version, I wonder if a simpler solution would suffice. Since you are clearly very careful about upgrading breaking changes, choosing to not upgrade seems like a manual process for you. If it is already manual, could you just exclude that package from ncu?

```
ncu -p -x react
```

FYI I still think for "frequently do[ing] not-breaking versions updates", using non-breaking version ranges (i.e. `^` with `npm update`) is still often the best solution.

Thanks, let me know what you think!

**Comment by karanjthakkar** [comment]
@raineorshine Sorry for the late reply. Happy new year! 🎆 

I'm currently on the latest version of ncu - `2.8.9`. Personally I think `semverLevel` provides much finer control over the updates I want to make to my packages. I find it to be of good use and would love to know if there are specific issues you are facing with maintaining it.

The thing about `ncu -p -x react` is it would just never show me any updates for the package `react` which is not what I want. I just want it show me stable releases for the package in the semver range that I provide.

As for using a `^` for non-breaking version range updates, we have been bitten in the past by package authors accidentally pushing breaking changes without a major semver bump, so we like to lock it down to specific versions and then upgrade them on bi-weekly or a monthly cycle.

I realise this is a much more custom requirement and I am not very sure if it is just me or if there are many projects which follow this same routine.

**Comment by raineorshine** [comment]
Thanks for your thoughtful response. While it may not be a typical use case, I would like npm-check-updates to be as flexible as possible for anything that's not directly a bad practice. 

It's unfortunate that sometimes prereleases get published to the latest tag, but I guess it's common enough to warrant some intelligence in ncu to handle it intuitively. 

I would suggest that we implement this as a major version bump, making the default be no prerelease versions unless --pre provided (which will be auto enabled for --greatest).

What do you think?

(I would like to first release this change itself as a prerelease because there are several breaking changes that need to be batched into the next major version.)

**Comment by karanjthakkar** [comment]
@raineorshine Thanks. Yes that sounds good to me. Just one question: since we are thinking of keeping `no prerelease versions` as default, wouldn't the `--pre` flag just be an enhancement? Why should this be a breaking change?

**Comment by raineorshine** [comment]
Currently npm-check-updates does not filter out prerelease versions. It
takes whatever is published as latest. Thus it would be a new, breaking
change to ignore prereleases by default. Granted, it would only cause a
breaking change for libraries that publish a prerelease as latest. Not a
huge breaking change, but breaking nonetheless.

That is, unless you see ncu's behavior of trusting what is published as
latest as a bug. I suppose you could argue it either way. Then this would
just be a patch. This behavior has existed long enough however that I think
it would be safer to include it in a major version bump in case anyone is
relying on the existing behavior. It would be unfortunate if someone
upgraded ncu and it caused one of their dependencies Togo backwards!

**Comment by karanjthakkar** [comment]
@raineorshine I'm sorry. My bad. I misread that. I get why it needs to be a breaking change.

**Comment by raineorshine** [comment]
Cool! I am traveling abroad for the next couple weeks, but I'll put this on
my list. Let me know if you want to help, it's always welcome.

**Comment by karanjthakkar** [comment]
@raineorshine I'd love to help out here. If you can show me a starting point I can take it up from there.

**Comment by raineorshine** [comment]
Awesome! 

The additional check belongs in the `./lib/package-managers/npm` module because that is where `latest` is located. The definition of [`latest`](https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L110) is simple:

```
cint.partialAt(view, 1, 'dist-tags.latest')
```

In less FP-style:

```
function (dep) { 
  return view(dep, 'dist-tags.latest');
}
```

The intended change would be:
- IF: the latest tag is not a prerelease version, use it.
- ELSE: use the highest numbered version that is not a prerelease (i.e. `view('versions').then(function(versions) { return _.last(versions.filter(...)) })`).

In version-util, there is a [`getPrecision`](https://github.com/tjunnone/npm-check-updates/blob/master/lib/version-util.js#L82-L86)  function. This will return `'release'` (or `'build'`) for prerelease versions. Use this in the filter predicate to filter out prereleases in the `latest` function.

Once this change is made, I will release a pre-release version of ncu. Other major version changes will be added before releasing v3 on the latest tag.

Thanks! Let me know if you have any questions!

**Comment by karanjthakkar** [comment]
@raineorshine So if I'm understanding this correctly, with the changes you mentioned above, the `--pre` flag would not affect the results if you are using the `--semverLevel` option since they use their own methods like `greatestMinot`, `greatestMajor`.

**Comment by raineorshine** [comment]
Good point. Now that I think about it, those should also be filtered.
