### ISSUE TITLE
--silent doesn't work

### ISSUE THREAD

**Issue by raineorshine** [tjunnone/npm-check-updates#317]
* node version: 6.1.0 
* npm version: 3.8.6
* npm-check-updates version: 2.8.9

---------------------------

`--silent` should behave the same as `loglevel --silent`. This appears to be a regression.

**Comment by karanjthakkar** [comment]
@raineorshine This seems to occur because the loglevel option defaults to `warn`. Because of that, [this line](https://github.com/tjunnone/npm-check-updates/blob/215792f0714d4f2d28f8db0e732a5a82873e1319/lib/npm-check-updates.js#L347) does not convert `options.silent` to `options.loglevel = 'silent'`. I'm not sure if this is recent regression. The commit where those changes happened are old: https://github.com/tjunnone/npm-check-updates/commit/18b3bb459fb70a31d0af48703f856146715b7287 Am I missing something or did this never work?

**Comment by raineorshine** [comment]
This is indeed a regression and worked only a long time ago. (Missed due to
lack of unit test!)

**Comment by raineorshine** [comment]
Fixed in `v2.10.2`
