### ISSUE TITLE
Unsatisfyable dependencies

### ISSUE THREAD

**Issue by silverwind** [tjunnone/npm-check-updates#318]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v7.4.0
* npm version: 3.10.2
* npm-check-updates version: 2.8.9

---------------------------

When a dependency is set to a newer version than what is available on npm, `ncu` wrongly tells me that "All dependencies match the latest package versions" (They actually don't match). Here's an example;

### `package.json`
````
"grunt-contrib-clean": "^1.0.1"
````
### `npm info grunt-contrib-clean`
````
  versions:
   [ '0.1.0',
     '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.4.0-a',
     '0.4.0-rc5',
     '0.4.0-rc6',
     '0.4.0',
     '0.4.1',
     '0.5.0',
     '0.6.0',
     '0.7.0',
     '1.0.0' ],
````

I think two improvements could be made:

- A warning could be issued that a dependencies' semver requirement cannot be satisfied with what's available on npm.
- A switch could be introduced to change the package version to match the latest from npm, even if it has to be downgraded in process.

**Comment by raineorshine** [comment]
Thanks for taking the time to report.

I can see how the "All dependencies match" message would be be confusing if there are invalid versions present that are being ignored. The current behavior is in order to prevent ncu from failing with various unrecognizable version numbers that nevertheless still might be "valid" for the project owner: private repos, github urls, specific commits, etc. That said, this could definitely be improved to handle a valid that semver version that fails to resolved, and provide a more appropriate error message.

I prefer the warning over any kind of downgrading behavior, although we could report the real latest (and highest) versions of the library to help people out.

I'll put this on my list of enhancements. Of course, always open to pull requests! Thanks.
