### ISSUE TITLE
ncu -t no longer works

### ISSUE THREAD

**Issue by gajus** [tjunnone/npm-check-updates#322]
* node version: v7.5.0
* npm version: 4.1.2
* npm-check-updates version: 2.10.0

---------------------------

Stopped working after updating `npm-check-updates` from 2.8.10 to 2.10.0.

My `package.json`:

```
{
  "ava": {
    "babel": "inherit",
    "require": [
      "babel-register"
    ]
  },
  "dependencies": {
    "@applaudience/showtime-data-management-program": "^1.11.0",
    "@applaudience/showtime-scraper-tools": "^0.3.0",
    "ajv": "^4.11.2",
    "body-parser": "^1.16.0",
    "debug": "^2.6.0",
    "express": "^4.14.1",
    "tmp": "0.0.31"
  },
  "devDependencies": {
    "ava": "^0.18.1",
    "babel-cli": "^6.22.2",
    "babel-plugin-transform-flow-strip-types": "^6.22.0",
    "babel-preset-env": "^1.1.8",
    "babel-register": "^6.22.0",
    "eslint": "^3.15.0",
    "eslint-config-canonical": "^7.1.0",
    "flow-bin": "^0.38.0",
    "husky": "^0.13.1"
  },
  "private": true,
  "scripts": {
    "lint": "eslint ./src ./test && flow",
    "precommit": "npm run lint && npm run test",
    "test": "ava --verbose --concurrency 1 --serial"
  }
}

```

Behaviour using v2.10.0 (unexpected):

```
ncu -t
Using /Users/gajus/Documents/dev/applaudience/showtime-data-sources-runner/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠴ :
All dependencies match the greatest package versions :)

```

Behaviour using v2.8.0 (expected):

```
ncu -t
Using /Users/gajus/Documents/dev/applaudience/showtime-data-sources-runner/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠏ :
 ajv      ^4.11.2  →   ^5.0.1-beta.3
 express  ^4.14.1  →  ^5.0.0-alpha.3

Run ncu with -u to upgrade package.json

```

**Comment by karanjthakkar** [comment]
Hey @gajus, this seems to be because of [this commit](https://github.com/tjunnone/npm-check-updates/commit/c11204a37647837487d825cc211b8d037dc66561) which changed the default behavior to hide prereleases. If you run `ncu -t --pre`, then you should get the expected output. Sorry about the breaking change! We should have ideally released this in a 3.x release instead of a 2.x one.

@raineorshine Was there a reason why we did not bump the major version while releasing [this PR](https://github.com/tjunnone/npm-check-updates/pull/311)?

**Comment by raineorshine** [comment]
Eek, my mistake! Didn't think through that. I will push a fix.

btw, greatest should implicitly specify --pre. Not sure why I didn't
realize this before.

**Comment by jharris4** [comment]
I just noticed the `--pre` change as well. I kind of wonder whether it should default to true to maintain backwards compatibility.

Also, I find **having** to use `--pre` for packages that are already pre-releases to be a bit annoying/unintuitive.

For example, I have `"react-select": "^1.0.0-rc.2"` in my package.json, and `1.0.0-rc.3` was just released. I wouldn't expect to **have** to use `--pre` to see updates for this package.

Maybe we can check the version of each package in package.json and if it looks like a pre-release then we should default to looking for pre-release updates for that package?

**Comment by raineorshine** [comment]
@jharris4 Thanks again for reporting. This was a mistake. It should be reverted in v2.10.1.

The bottom line is that package authors should *not* be releasing pre-release packages under the `latest` tag. As long as they do that, you won't have any problems. Nevertheless, accidents happen or people have unconventional approaches to package management. In that case we have a choice of how to handle a prerelease versions that are published as latest. I don't think there is a single solution that will work for everyone, but after numerous issues being reported where the underlying issue was the dependency, it seems that the most intuitive behavior is to filter out prerelease versions by default. Since this is a backwards-incompatible change, it will be (properly) published in the next major version update. The `--pre` option will provide backwards compatibility for the old behavior.

> I have "react-select": "^1.0.0-rc.2" in my package.json, and 1.0.0-rc.3 was just released. I wouldn't expect to have to use --pre to see updates for this package.

This makes a lot of sense. What do you think @karanjthakkar? I don't like to introduce too much polymorphism (that's exactly what got us intro trouble with ignoring installed packages), but this seems quite straightforward and intuitive if they explicitly specify a prerelease as a dependency. I think we should update the feature accordingly.

**Comment by karanjthakkar** [comment]
@raineorshine Yes, in this specific case I think we should be showing prereleases to the user. But then I am not very happy with implicitly doing something for a certain set of dependencies (filtering out prereleases) and something else for another set (showing the next prerelease version). 

Do you think a better idea would be to have ncu works as is before we introduced `--pre` and then changing `pre` to `no-pre` and giving the user an option to filter out prereleases? That would solve the OP's problem and also fix the reason why I opened #311.

**Comment by raineorshine** [comment]
On principal, yes, but I think in this case it's pretty intuitive. Furthermore, semver has a precedent:

`"lodash": "^1.0.0"` will *not include* prelease versions
`"lodash": "^1.0.0-rc.1"` will *include* prelease versions

Using `--no-pre` (opt-in) instead of `--pre` (opt-out) I believe is a less adequate solution for the average user. It will help more people having a behavior that mitigates poor publishing practices (i.e. releasing a pre-release to the latest tag) than the people it will hurt by filtering out preleases by default, which could be close to 0.

This is more of a judgment call than a right/wrong solution. I base my intuition on observing the rate of issues related to pre-release versions over time.

**Comment by raineorshine** [comment]
Closing as original issue has been fixed. Please open a new issue if you would like to discuss future behavior of the upcoming `--pre` flag.
