### ISSUE TITLE
Ironically your dependencies are out of date! 

### ISSUE THREAD

**Issue by grantcarthew** [tjunnone/npm-check-updates#331]
- [ x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

This hit my radar because you have a dependency for `npm` that depends on `request` that depends on `node-uuid` which is deprecated.

**Comment by grantcarthew** [comment]
I just saw this commit:
https://github.com/tjunnone/npm-check-updates/commit/5efc9152b3c64a20e9992e819b6886b371b7e5be

**Comment by raineorshine** [comment]
Thanks for reporting! Do you know the best way to remedy this?

**Comment by grantcarthew** [comment]
Hehe, I don't think I understand the question @raineorshine.

My answer would be to install `npm-check-updates` globally and then run it against the `package.json` in the `npm-check-updates` package.

Run tests and you are done.

I didn't do this myself because it seems more like a maintainers job.

**Comment by raineorshine** [comment]
When I run `npm-check-updates` on `npm-check-updates` itself, I get the following output:

```
 find-up            1.1.2  →   2.1.0
 npm              ^3.10.6  →  ^4.3.0
 update-notifier   ^1.0.2  →  ^2.1.0
```

- `find-up` has a breaking change that is not compatible with `npm-check-updates`, so it needs to stay on `1.x`.
- `npm` will be removed as a direct dependency in the next major version of `npm-check-updates` and will instead be used as a peer dependency in order to support users with different versions of `npm`.
- `update-notifier` was recently bumped to `v2` in order to use es6 features, deprecating node 0.10 and 0.12. `npm-check-updates` is continuing to support older node versions so we don't want to upgrade this.

No other dependencies are out of date. If there are dependencies of dependencies that are deprecated, that will need to be addressed with the appropriate package owners.

Let me know if I'm missing something!

**Comment by grantcarthew** [comment]
OK, thanks for the more detailed response @raineorshine.

I was just raising this because of the deprecation warning in the console. `npm` was the only warning so if that is getting removed as a direct dependency then that will be fixed.

Thanks again. Not trying to bother you, just trying to help.

**Comment by raineorshine** [comment]
Absolutely! Appreciate your input.
