### ISSUE TITLE
Does not update pacakge.json when running under crontab

### ISSUE THREAD

**Issue by AlexShemeshWix** [tjunnone/npm-check-updates#342]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.9.1
* npm version: 3.10.8
* npm-check-updates version: 2.11.0
---------------------------

Im keeping my packages up to date with ncu.
It runs ok when i run it manually ( no sudo)
But it will not change package.json when it runs under crontab 
The target file has 777 permissions.
Ive tried to use sudo, no effect
Ive tried to use verbose logging, no errors found.
Ive tried to run it under root user, no effect.
When it runs it prints out target package.json full path properly, and it prints out what version will be updated, but it wont print "Upgrading ..." message in the end.
Please help

**Comment by raineorshine** [comment]
Hi! Thanks for reporting! It sounds like you have tried lots of things to no avail.

I think this question might be more appropriate for StackOverflow since it involves a unix tool. ncu works fine on its own, as you pointed out, so there must be some issue with crontab not passing the `-u` argument.

Maybe somebody with experience with crontab can offer a suggestion here, otherwise I would recommend asking on StackOverflow. The usage of contab and its interaction with libraries like ncu is beyond my shell skills. Thanks for your understanding!
