### ISSUE TITLE
-a option doesn't work

### ISSUE THREAD

**Issue by NinoDLC** [tjunnone/npm-check-updates#343]
My package.json is like that : 
```
{
  "name": "xxx",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.17.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.3",
    "express": "~4.15.2",
    "jade": "~1.11.0",
    "morgan": "~1.8.1",
    "serve-favicon": "~2.4.2",
    "socket.io": "~1.7.3"
  }
}
```

debug v2.6.4 is out, but even with the -a command (`ncu -a -u`), it doesn't update the package.json...

* node version: ?
* npm version: 4.2.0
* npm-check-updates version: v2.11.0

**Comment by raineorshine** [comment]
Thanks for reporting! May I ask, what is your installed version of debug?

**Comment by NinoDLC** [comment]
I don't understand the question, it is 2.6.3 as mentioned in the JSON ? `"debug": "~2.6.3"`

Or am I missing something ? (I'm quite new to node.js)

**Comment by raineorshine** [comment]
@NinoDLC You can determine the installed version by running `npm ls debug`.

The version listed in your package.json is a version range (due to the `~`) so any number of versions that fit that version range could be installed. If you have v2.6.6 installed, npm-check-updates currently *will not* update your package.json, as you have the very latest installed and your specified dependency includes that version, so there is no reason to upgrade the package.json. Although logical, this behavior is still confusing to many people, so in the next major version of npm-check-updates we will be removing all installation version checking and just blindly updating the package.json when `-a` is specified.

**Comment by NinoDLC** [comment]
Ok thanks for the infos !

**Comment by raineorshine** [comment]
@NinoDLC Any luck finding the debug version? Was the issue that the installed version was up-to-date?
