### ISSUE TITLE
Update Package.json to the installed dependencies instead of very latest available

### ISSUE THREAD

**Issue by Sibiraj-S** [tjunnone/npm-check-updates#348]
Why can we able to update package.json only to the latest dependency version that is being installed locally instead of updating to the very latest version.

It would be nice if we also have an option  to update package.json to the locally installed dependencies

**Comment by raineorshine** [comment]
If you have a locally installed dependency, wouldn't that imply that you have a package dependency specified that includes that? The only case I can think of where this wouldn't be true is if you do `npm install x` instead of `npm install --save x`.

I could be wrong here, but I wonder if there is also [confusion related to dependency ranges](https://github.com/tjunnone/npm-check-updates#why-is-it-not-updating-100-to-101-when-101-is-the-latest).

Let me know if that helps or if I am missing something!

**Comment by Sibiraj-Codes** [comment]
actually, ncu is a very nice. each time `npm install x --save` for everything is little difficult

I came across something if that kind of option is available in `ncu`. I think `ncu` will be complete.

This a feature in vs code. `https://github.com/vscode-contrib/vscode-versionlens`.

Can you check this. No offence. 😀

**Comment by raineorshine** [comment]
So are you mainly looking for a way to display not just latest but beta versions as well?

**Comment by Sibiraj-Codes** [comment]
yeah maybe. but installed version + latest version. beta version can be optional.

**Comment by Sibiraj-Codes** [comment]
I think I am asking for a feature request not an issue.

**Comment by raineorshine** [comment]
I see! The beta version would indeed be a new version. To compare installed versions, I would recommend the built-in `npm outdated` command.

**Comment by Sibiraj-Codes** [comment]
yeah. enhancement. looking forward to it. 😀

**Comment by Sibiraj-S** [comment]
this feature is introduced in `npm v5`

**Comment by Sibiraj-S** [comment]
closing this issue as `npm v5` has a native support for it. using `npm update`
