### ISSUE TITLE
Exclude alpha/beta/rc packages

### ISSUE THREAD

**Issue by skorunka** [tjunnone/npm-check-updates#368]
- [ x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.1.0
* npm version: 5.4.0
* npm-check-updates version: 2.11.3

---------------------------
package.json
"zone.js": "0.8.12"

ncu:
rxjs  5.4.0  →  6.0.0-alpha.0
Run ncu with -u to upgrade package.json

Any chance to do not include alpha, beta, rc versions in the list of update candidates?

**Comment by raineorshine** [comment]
Thanks for reporting! Luckily I am familiar with this issue, let me see if I can explain.

First, I consider it a mistake for package authors to upload prerelease versions to the `latest` tag. `npm install` always installs from the `latest` tag. Package authors can publish packages to other tags as well. If they publish a version of their package under `alpha` for example, users can install it with `npm install NAME@alpha`. The problem you are experiencing with `rxjs` is a problem not just for npm-check-updates users, but normal `npm` users as well who expect that `latest` will install the latest stable version.

This has happened a few times now, with surprisingly prominent libraries, so it is reasonable to consider if npm-check-updates can do anything to mitigate this upstream problem. We decided that most users assume that prereleases will *not* be included so we added a feature to filter out prerelease versions as the default, with an option to opt-out. Since this is a breaking change, it will be included in the [v3 milestone](https://github.com/tjunnone/npm-check-updates/milestone/2).

You can follow the specific issue here:
https://github.com/tjunnone/npm-check-updates/issues/308

Thanks!

**Comment by skorunka** [comment]
Lovely! Thank you.

**Comment by julmot** [comment]
Having the same situation:

![2017-09-19 14_24_51-cmd](https://user-images.githubusercontent.com/8310677/30592249-51663924-9d46-11e7-986c-f1a4b432da49.png)

I don't want to update to beta versions.

**Comment by raineorshine** [comment]
@julmot This was a decision that the `swiper` package author made, so unfortunately they want you to upgrade. Feel free to post an issue with them to say it is not recommended to post beta versions to the `latest` tag. You'll have to exclude swiper from ncu if you do not want to upgrade.

**Comment by apaatsio** [comment]
I'm a bit confused here. I have `"immutable": "4.0.0-rc.9"` defined in my package.json. If we check the info on the immutable package we see that `4.0.0-rc.9` is tagged as `rc` and the `3.8.2` is tagged as `latest`. 

```
❯ npm view immutable | grep "dist-tags"
  'dist-tags': { latest: '3.8.2', rc: '4.0.0-rc.9' },
```

When I run `ncu` it says `All dependencies match the latest package versions :)`.

There is `4.0.0-rc.9` in the package.json and it's also installed but the `latest` is `3.8.2`. How can the versions match?

For my use case, this is actually the desired behavior but I think the text `All dependencies match the latest package versions :)` is misleading.

**Comment by raineorshine** [comment]
@apaatsio I agree. Maybe we can change the text in this case: ncu will never upgrade to a latest version that is lower than the specified version.

**Comment by raineorshine** [comment]
Most of the logic of this has already been done in https://github.com/tjunnone/npm-check-updates/pull/311/files. See that PR to understand where the filtering occurs.

For v3 we need to also filter out packages with versions containing `-alpha`, `-beta`, or `-rc`, even if they are published to the `latest` tag. The `--pre` option (already implemented) allows users to opt-in.

**Comment by raineorshine** [comment]
Implemented and ready to be published
