### ISSUE TITLE
Problem running ncu on OS X

### ISSUE THREAD

**Issue by eddieedease** [tjunnone/npm-check-updates#385]
- [ x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v6.11.2
* npm version: 5.3.0
* npm-check-updates version: error

---------------------------
On windows & linux I have everything working as expected. However, on OS X, not so much.
When calling `ncu` or `npm-check-updates` from command line i get.

`Error: Cannot find module 'ansi'`
After installing with `npm install -g ansi` i get
`Error: Cannott find module 'lodash.pad'` after installing that it goeson with 'lodash.padon' missing and it goes on.

I tried installing: browser sync with `npm install -g browser-sync` because the packages above seem to fall under that package... but it didn't work

**Comment by raineorshine** [comment]
Hi! Thanks for reporting. I'm sorry you are experiencing difficulties. I am
running OSX and unfortunately I can't reproduce the issues you are
experiencing. This leads me to believe that it is not a problem with
npm-check-updates, but npm, which occasionally does not install
dependencies correctly and leads to problems like this. If you can send a
repo in which this is reproduced, I would be happy to troubleshoot,
otherwise there might not be much I can do! You may have to play around
with your node and npm installation to get it to work. Try doing a full
uninstall and re-install of ncu, and then if that doesn't work possibly
doing that for node.

**Comment by eddieedease** [comment]
I got it fixed. I don't know how exactly, but you were right. I think it happened when I downgraded my nodejs + npm.

So, if anyone else runs into this. Just.
- `npm uninstall -g npm-check-updates`
- `npm cache clean --force`
- `npm i -g npm-check-updates`

Thanks for the response, great tool!

**Comment by raineorshine** [comment]
Yay! 🐼

**Comment by bryanSME** [comment]
having the same issue on OSX. no problems on ubuntu. I know it's not a very good fix but hopefully this will help someone else. Add the following to your bashrc. 

`PATH=$PATH:/Users/__YOUR_USERNAME_/npm_global/lib/node_modules/npm-check-updates/bin`

then, `source ~/.bashrc`
