### ISSUE TITLE
ncu reports no updates after running "npm install"

### ISSUE THREAD

**Issue by joliss** [tjunnone/npm-check-updates#424]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 9.5.0
* npm version: 5.6.0
* npm-check-updates version: 2.14.0

---------------------------

npm-check-dependencies correctly reports package upgrades on a pristine clone of the following npm package:

```
$ git clone https://github.com/joliss/broccoli-coffee -b v1.0.0
...
$ cd broccoli-coffee/
$ ncu
Using .../broccoli-coffee/package.json
[..................] \ :
The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using npm update. If you want to update the dependencies in your package file anyway, run ncu -a.

 broccoli-persistent-filter  ^1.1.5  →  ^1.4.3
 json-stable-stringify       ^1.0.0  →  ^1.0.1
```

But once I run `npm install`, it stops reporting upgrades:

```
$ npm install
added 180 packages in 2.371s
$ ncu
Using .../broccoli-coffee/package.json
[..................] | :
All dependencies match the latest package versions :)
```

I'm not entirely sure why this is would be happening. Please let me know if you can reproduce the problem. If not, I'm happy to investigate more.

**Comment by raineorshine** [comment]
Hi! Thanks for reporting!

What you are seeing is an unintuitive behavior that is intended to be removed in the next major version update. Once you run `npm install`, `ncu` sees that you have the latest version of `broccoli-persistent-filter`, for example, installed in node_modules and assumes that you do not need to update your package.json. 

This is the one case where `ncu` looks at `node_modules`. This causes confusion for others. It was fixed in https://github.com/tjunnone/npm-check-updates/commit/71386c98ba581abf1c6ff88c1f6a86bfa06788ad but has been delayed due to waiting for `v3` to be finished. (Active development ceased months ago due to time constraints; I have been the only contributor for several years. See [v3 milestone](https://github.com/tjunnone/npm-check-updates/milestone/2) and most importantly ).

See https://github.com/tjunnone/npm-check-updates/issues/263 for history and details of the previously reported issue.

**Comment by joliss** [comment]
Thanks for detailed explanation @raineorshine! I'm looking forward to the next version!
