### ISSUE TITLE
beta is suggested in ncu

### ISSUE THREAD

**Issue by dereklin** [tjunnone/npm-check-updates#455]
- [x ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v8.11.0
* npm version: 6.1.0
* npm-check-updates version: 2.14.2

---------------------------
We have noty 3.1.4 in our package.json's dependency list.  ncu is suggesting a beta version upgrade.  Is there any flag I need to use to ignore all the beta version?

```
noty                                              3.1.4  →     3.2.0-beta
```

**Comment by raineorshine** [comment]
`noty` has published their beta to the `latest` tag, which is why ncu is suggesting the upgrade. I recommend asking the `noty` authors to consider publishing beta versions to a different tag.

It would be great to a PR in ncu to parse the version number and exclude packages with `-alpha`, `-beta`, or `-rc`.

**Comment by jacobq** [comment]
I think it makes sense to ignore releases with semver labels like `x.y.z-beta.1` **if and only if** the version specified in the `package.json` does not include that label. However, it would be super nice if `ncu` would suggest upgrading a package from, say, `2.0.0-rc.1` to `2.0.0-rc.2` once that newer release candidate is out.

Call me an early adopter, but I use `ncu` largely because I usually want to try my code against the absolute latest published versions--whether stable releases, pre-releases, betas, etc.--with the exception that I usually don't want nightlies.

**Comment by raineorshine** [comment]
v3 now ignores prerelease tags by default. Old behavior available with `--pre`. More complicated logic based on prerelease versions specified in the package.json have not been implemented. PR's welcome. Thanks!

 https://github.com/tjunnone/npm-check-updates/releases/tag/v3.0.0

**Comment by julmot** [comment]
Great, thank you very much!
