### ISSUE TITLE
Check if packages are compatible with installed version of node

### ISSUE THREAD

**Issue by Vlasterx** [tjunnone/npm-check-updates#47]
I have extremely negative experience with this plugin. It checks newest versions for NPM packages and updates package.json with latest versions, but unfortunately doesn't check if those versions are compatible with installed node.js version. 

Somehow it worked on my computer, I managed to update all packages to latest with `npm install`, but no other computer managed to reproduce this, even with same node.js and npm version installed. Now I'm left with completely ruined versions of numerous plugins and will have to start everything from scratch...

**Comment by metaraine** [comment]
Hi Vladimir. I'm sorry you had a bad experience. I agree that sucks to have
your versions messed up. I would recommend committing everything to git
before running npm-check-updates. In the mean time, I will look into
checking compatibility with node versions, that should probably happen.
Thanks.

On Sun, Feb 8, 2015 at 3:21 PM, Vladimir Jovanovic <notifications@github.com

**Comment by Vlasterx** [comment]
I am using git, but unfortunately I have been using this plugin for updates regularly since early start of those projects, 3-4 months ago, so bringing files from repository won't do much. Somehow, this plugin did update package versions, I managed to update them at that time, but when I pull the same repo on another computer, instalation of those packages fails. 

But thanks for the quick answer. This is issue you should keep in mind. Who knows, maybe someone else runs into this problem as I have.

**Comment by MrHyde** [comment]
Im using this module for almost two years and never got any trouble with it. But i think author problems is not related to `ncu` at all, and it's related more to project management and good practices.
1. You should always commit your changes and keep clean and tidy project history.
2. You should always check for plugin compatibility (tests ftw)
Following this simple rules it's literally impossible to "ruin" your project.
`ncu` just helps you with routine but it's your responsibility to use it wisely 

Also, checking for engine version could cause more problems than benefits, since a lot of plugins still targeting 0.8 version of node js :disappointed:

**Comment by metaraine** [comment]
@MrHyde: Great points, thank you!

**Comment by jduprey** [comment]
This would be a helpful feature.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.
