### ISSUE TITLE
Wrong color, patch update shows in red instead of green

### ISSUE THREAD

**Issue by Pustur** [tjunnone/npm-check-updates#534]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: `11.5.0`
* npm version: `6.9.0`
* npm-check-updates version: `3.1.8`

---

Hey, just a small issue I ran into, here marked shows a patch update but it's shown in red color (which should only happen for major updates)

<img width="316" alt="Screenshot 2019-04-21 at 19 08 56" src="https://user-images.githubusercontent.com/13663338/56473331-34ffc880-646a-11e9-9fe4-e2ac63ece183.png">

I tried to make an empty new project, install only marked `0.6.0` and then run `ncu` the result is the same.

It's a small thing but I figured I'd let you know.

**Comment by stoically** [comment]
["Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."](https://semver.org/#spec-item-4). Hence every major version 0 is marked red because it's potentially a breaking change. Might be worth mentioning in the README though.

**Comment by Pustur** [comment]
@stoically Ohh ok that makes sense. Yeah I think this should be mentioned somewhere.

Thanks for the clarification!
