### ISSUE TITLE
should not update when version is `~`

### ISSUE THREAD

**Issue by bluelovers** [tjunnone/npm-check-updates#540]
should not update when version is `~`

like ~2 will only v2.x.x, not  version> 3 by default

only update when other flags is set

**Comment by raineorshine** [comment]
If I am understanding you correctly, you are saying that a dependency specified as `~2.0.0` should not be upgraded by npm-check-updates to `~3.0.0`?

If that is the case, unfortunately that would be the opposite of what npm-check-updates is intended for. The purpose of npm-check-updates is to upgrade your dependencies so that they *break* and then you can fix backwards-incompatibilities manually. If you would like to stay within a version range, simply use npm and semver as-is.

**Comment by tdukai** [comment]
At least it should honor the =3.0.0 flag and NOT upgrade!

**Comment by stoically** [comment]
The purpose of ncu is to upgrade your dependencies, not to honour your semver flags. If you want to exclude something from upgrading, you can use the `-x` flag, or use `-i` to interactively choose what should be upgraded (which is essentially what @raineorshine already said).
