### ISSUE TITLE
Differences between this and salita?

### ISSUE THREAD

**Issue by davemac** [tjunnone/npm-check-updates#58]
Not an issue, but a question what are the differences between this and https://github.com/tbranyen/salita besides the coloured output?

I this is not the best forum to discuss this, please let me know where we can.

**Comment by metaraine** [comment]
Not sure the best place for this either, but great question. Here's what I have gleaned. I've left out features they both have, as well as features whose only difference is opt-in/opt-out.

## npm-check-updates (2.0.0-alpha.7)
- unit tests
- preserves versioning format given in package.json (e.g. 1.x -> 2.x)
- looks into descendant directories for the closest package.json
- can filter by package name via string or regex
- can target dependencies, devDependencies, or both.
- can optionally update to unstable versions
- can check global packages

## salita (0.7.0)
- elegant, colored output
- can specifically ignore updates to packages that are pegged to a single version, rather than a range
- json output
- can return an exit code equal to the number of packages that need updating

I added this to the [wiki](https://github.com/tjunnone/npm-check-updates/wiki/npm-check-updates-vs-salita) in case it is helpful for others.

**Comment by geminiyellow** [comment]
@metaraine can it check all packages? dependencies's dependencies's dependencies's ...

**Comment by metaraine** [comment]
It does not. Is there a use case for this? It seems that most dependencies
of dependencies would be 3rd party modules that you couldn't update even if
there were modules to bump.
