### ISSUE TITLE
ncu cannot detect update for a package with uncommon versioning

### ISSUE THREAD

**Issue by Simek** [tjunnone/npm-check-updates#615]
Currently `ncu` cannot detect update for the package:
https://www.npmjs.com/package/reanimated-bottom-sheet

Version string for this package looks like `1.0.0-alpha.X` where X is bumped every release. 

* node version:  13.1.0
* npm version:  6.12.1
* npm-check-updates version: 3.2.2

**Comment by raineorshine** [comment]
Thanks for reporting. This will be fixed with a breaking change in v4.

ncu v3 excludes prerelease versions from the remote by default, as publishing prerelease versions to `latest` is unconventional and in my opinion not recommended. Prereleases versions can be included by specifying `--pre` (and is implied in options `--greatest` and `--newest`).

However, when you are already specifying a prerelease version in your package.json dependencies, then clearly you want ncu to find newer prerelease versions. This will become default in v4, albeit with the conservative approach of sticking to the `latest` tag.

**Comment by raineorshine** [comment]
Published in `v4.0.0`

**Comment by Simek** [comment]
@raineorshine Unfortunately `4.0.0` don't fixed reported issue for me. If `reanimated-bottom-sheet` is sole outdated dependency `ncu` works as intended. But when there are more outdated dependencies (and not `pre` scope) `reanimated-bottom-sheet` is not being displayed on the list.

<img width="461" alt="Screenshot 2019-12-10 at 18 51 17" src="https://user-images.githubusercontent.com/719641/70554893-4f63ef00-1b7e-11ea-8ea5-db02ef15f80a.png">

**Comment by raineorshine** [comment]
Good catch. That one made it past the unit test.

Try `v4.0.1`.

**Comment by Simek** [comment]
I can confirm that `4.0.1` fixed this issue, thank you!
