### ISSUE TITLE
option to replace keyword latest by actual latest version

### ISSUE THREAD

**Issue by vesper8** [tjunnone/npm-check-updates#632]
I've inherited a project where the package.json is full of dependencies that are pointed to `latest` as a version. I find this a bit troubling and would rather it be pointing to actual versions to prevent unintended upgrades in the future

I noticed that npm-check-updates is ignoring these, because they are already the latest I imagine. I was wondering if there's a way to have this package swap out `latest` by the actual latest version in the package.json ?

**Comment by raineorshine** [comment]
The easiest way I can think of is to replace all `latest` with `0.0.0` and then run `ncu -u`.

The reason this is not default is because `npm-check-updates` is committed to maintaining `existing semantic versioning policies, i.e. "express": "^4.0.0" to "express": "^5.0.0"`. It's an important invariant in `npm-check-update`'s design. I do agree that `latest` in one's `package.json` is not a good practice.

**Comment by vesper8** [comment]
Thanks for the reply. I might try that next time. What I did this time is I selected all the deps that were set to latest using multiple cursors, and then I ran `yarn add --save` on all those packages and that got the latest versions and overwrote the `latest` with the version
