### ISSUE TITLE
wrong version number

### ISSUE THREAD

**Issue by stevemao** [tjunnone/npm-check-updates#65]
If I put a wrong version number, it says
"conventional-changelog" can be updated from 0.0.16 to 0.0.15 (Installed: 0.0.15, Latest: 0.0.15)

I think it should say
"conventional-changelog" 0.0.16 doesn't exist. 0.0.15 is the latest version (Installed: 0.0.15, Latest: 0.0.15)

**Comment by metaraine** [comment]
Good point. It is possible however for a dependency to be at a higher version number than the "latest" tag, i.e. prerelease versions may exist. For that reason, I wouldn't want to say "doesn't exist" as maybe they are referencing a prerelease version on purpose. 

Since npm-check-updates is geared towards checking newer versions rather than catching package.json errors anyway, I'm okay with this tradeoff.

In the upcoming v2.0.0 (now available on the unstable tag as `2.0.0-alpha.7`) modules that are newer than the official "latest" are ignored, which at least removes the confusing message.

**Comment by stevemao** [comment]
Is this problem already solved?

**Comment by metaraine** [comment]
Yep... it is "solved" in v2.0.0-alpha.7. You can install this prerelease version of npm-check updates with `npm install -g npm-check-updates@unstable`. It doesn't contain the message that you suggested, but it behaves in a more intuitive way, ignoring newer version numbers since they could be alpha releases. Let me know if that needs more explanation!

**Comment by stevemao** [comment]
Great! thanks @metaraine
